# -- meta
model_name: "vit_huge"
patch_size: 14
crop_size: 224
num_classes: 100
batch_size: 256

# -- optim params
init_lr: 0.005
weight_decay: 0.0

# -- train
r_file: "./weights/target_encoder.pth"
num_epochs: 15
save_dir: "./output/run5"
resume_training: true